apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mb0q4z3t8-python 
  janus-idp.io/tekton: mb0q4z3t8-python
  backstage.io/kubernetes-id: mb0q4z3t8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mb0q4z3t8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml